---
title: "Replica artículo"
author: "Laura Martinez"
output:
  html_document:
    theme: flatly
    toc: false
    self_contained: true
    code_folding: hide
    mathjax: default
    css: estilos.css         # 👈 Vincula el CSS externo automáticamente
    includes:
      in_header: scripts.js # 👈 Vincula el JS externo en el header
editor_options: 
  markdown: 
    wrap: sentence
---

```{=html}
<!-- 🛠️ CONTENEDOR DE BOTONES FLOTANTES -->
<div class="action-buttons">
  <button id="theme-toggle" class="btn-floating" title="Cambiar Modo">🌓 Modo Oscuro</button>
  <button id="pdf-download" class="btn-floating btn-pdf" title="Descargar todo en PDF">📄 Descargar PDF</button>
</div>
```


# Statistical modeling of Dengue transmission dynamics with environmental factors {.tabset .tabset-fade}

## Módulo I: Base de datos




```{r, child='ModuloI.Rmd'}
# 👈 Este bloque mágico inserta todo el contenido del Capítulo 1 aquí
```

## Módulo II: replica de base de datos

### 📑 Índice rápido


::: index-box
-   [1. Fundamentos de los Campos Aleatorios Espaciales.](#seccion-2-1)
    *  [1.1 Fundamentos Matemáticos](#seccion-2-1-1)
    *  [1.2 Taller de Laboratorio](#seccion-2-1-2)
    *  [1.3 Implementación en R](#seccion-2-1-3)
    *  [1.4 Ejercicios del libro](#seccion-2-1-4)
-   [2. Funciones de semivarianza y autocovarianza espacial.](#seccion-2-2)
    *  [2.1 Fundamentos Matemáticos](#seccion-2-2-1)
    *  [2.2 Taller de Laboratorio](#seccion-2-2-2)
    *  [2.3 Implementación en R](#seccion-2-2-3)
    *  [2.4 Ejercicios del libro](#seccion-2-2-4)
-   [3. Predicción Espacial: Kriging y Cokriging.](#seccion-2-3)
    *  [3.1 Fundamentos Matemáticos](#seccion-2-3-1)
    *  [3.2 Taller de Laboratorio](#seccion-2-3-2)
    *  [3.3 Implementación en R](#seccion-2-3-3)
    *  [3.4 Ejercicios del libro](#seccion-2-2-4)
:::




